### ISSUE TITLE
Preparación de los datos:

### ISSUE THREAD

**Issue by julissah** [julissah/EDA-M#2]
-[ ] Generar varios conjuntos de datos (archivos .txt), por ejemplo va a generar números aleatorios y los va a almacenar en varios archivos. Cada archivo deber ́a contener respectivamente 100, 500, 1000, 2000, 3000, ... , 10000, 20000, 30000, ... ,100000
datos.

**Comment by davidlm12** [comment]
Se realizo la subida de 21 archivos, con el conjunto de números de aleatorios como datos.
